### ISSUE TITLE
example.rb

### ISSUE THREAD

**Issue by copremesis** [synth/omniauth-microsoft_graph#1]
``` bash
$ ruby example.rb
.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- omniauth-microsoft_graph (LoadError)
    from .rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from example.rb:2:in `<main>'
```

I then changed the top of the file to be:

``` diff
-require 'omniauth-microsoft_graph'
+require 'microsoft_graph'
```

and it now works 🐼 

```
$ ruby example.rb
[2016-06-22 08:03:11] INFO  WEBrick 1.3.1
[2016-06-22 08:03:11] INFO  ruby 2.3.1 (2016-04-26) [x86_64-darwin13]
== Sinatra (v1.4.7) has taken the stage on 4200 for development with backup from WEBrick
[2016-06-22 08:03:11] INFO  WEBrick::HTTPServer#start: pid=6031 port=4200
```

**Comment by synth** [comment]
Updated, Thanks!
